"use client";

import { useState, useEffect } from "react";
import { useAppContext } from "@/app/AppContext";
import { ShieldAlert } from "lucide-react";

export default function DisclaimerScreen() {
    const { siteSettings } = useAppContext();
    const [accepted, setAccepted] = useState(false);
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
        if (localStorage.getItem("casino_disclaimer_accepted")) {
            setAccepted(true);
        }
    }, []);

    const handleAccept = () => {
        setAccepted(true);
        localStorage.setItem("casino_disclaimer_accepted", "true");
    };

    if (!mounted || accepted || !siteSettings?.showDisclaimerScreen) return null;

    return (
        <div className="fixed inset-0 bg-slate-950/90 backdrop-blur-xl z-[999] flex items-center justify-center p-4">
            <div className="bg-slate-900 border border-slate-800 rounded-3xl p-8 max-w-lg w-full shadow-2xl flex flex-col items-center text-center gap-6">
                <div className="w-20 h-20 bg-red-500/10 rounded-full flex items-center justify-center">
                    <ShieldAlert className="w-10 h-10 text-red-500" />
                </div>
                
                <h1 className="text-3xl font-black text-white">PROTOTYPE NOTICE</h1>
                
                <div className="text-slate-400 space-y-4">
                    <p>
                        This application is a <strong>development prototype</strong> and is not a real casino.
                    </p>
                    <p>
                        <strong>THIS IS NOT REAL MONEY.</strong>
                    </p>
                    <p>
                        The cryptocurrency deposits use the <strong>Sepolia Test Network</strong>. Do not send real Ethereum or any other real cryptocurrency to the addresses generated by this application, or it will be permanently lost.
                    </p>
                </div>

                <button 
                    onClick={handleAccept}
                    className="w-full mt-4 bg-red-600 hover:bg-red-500 text-white font-bold py-4 rounded-xl transition-colors text-lg"
                >
                    I Understand
                </button>
            </div>
        </div>
    );
}
